<?php echo $this->pageTitle($this->translate('Nakala Importer')); ?>

<?php $this->trigger('view.index.before'); ?>

<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>

<?php $this->trigger('view.index.form.before'); ?>
<?php echo $this->formCollection($form); ?>
<?php $this->trigger('view.index.form.after'); ?>

<div id="page-actions">
    <button><?php echo $this->translate('Submit'); ?></button>
</div>

<?php echo $this->form()->closeTag(); ?>

<?php $this->trigger('view.index.after'); ?>
