<?php
$this->htmlElement('body')->appendAttribute('class', 'nakala__importer__jobs');
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('css/nakala_importer.css', 'NakalaImporter'));
?>

<?php echo $this->pageTitle($this->translate('Past imports'), 1, $this->translate('Nakala Importer')); ?>
<?php if (empty($imports)): ?>
    <?php $this->translate("None imports yet"); ?>
<?php else: ?>
<?php echo $this->pagination(); ?>

    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th>
                    <?php echo $this->sortLink($escape($this->translate('Date')), 'id');?>
                </th>
                <th><?php echo $escape($translate('Collections imported'));?></th>
                <th><?php echo $escape($translate('Status'));?></th>
                <th><?php echo $escape($translate('Owner'));?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($imports as $import): ?>
                <form method='POST'>

                    <?php $job = $import->job(); ?>
                    <?php $collectionsImported = $import->collectionsImported(); ?>

                    <tr id="import-<?php echo $import->id() ;?>">
                        <td>
                            <?php echo $escape($this->i18n()->dateFormat($job->started())); ?>
                        </td>
                        <td>
                            <?php echo $this->showCollectionsDetails($collectionsImported);?>
                        </td>
                        <td>
                            <div>
                            <?php echo $escape($translate($job->status()));?>
                            </div>
                            <span class="nakala-import-job-param">
                                <?php echo $this->hyperlink($this->translate('Job details'), $this->url('admin/id', ['controller' => 'job', 'action' => 'show', 'id' => $job->id()])); ?>
                            </span>
                            <?php if ($job->log()): ?>
                            /
                            <span class="nakala-importer-job-log">
                                <?php echo $this->hyperlink($this->translate('Log'), $this->url('admin/id', ['controller' => 'job', 'action' => 'log', 'id' => $job->id()]), ['target' => '_blank']); ?>
                            </span>
                            <?php endif; ?>
                        </td>
                        <td><?php
                        $owner = $job->owner();
                        if ($owner):
                            echo $this->hyperlink($owner->name(), $this->url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()]));
                        endif;
                        ?></td>
                    </tr>
                </form>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>