<tr id="set_<?php echo $identifier ?>">
    <td>
        <input class="set-checkbox" type="checkbox" name="selectedSets[<?php echo $identifier?>]" value="<?php echo $title ?>"/>
        <a href="<?php echo $uri ?>" target="_blank"><?php echo $identifier ?></a>
    </td>
    <td><?php echo $title ? $title : $this->translate('None Title') ?></td>
    <td><?php echo $status ?></td>
    <td><?php echo date('Y-m-d', strtotime($creation_date)) ?></td>
</tr>